version: '2'
services:
    firstapp-app:
        image: firstapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://firstapp-postgresql:5432/firstApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8282:8282
    firstapp-postgresql:
        extends:
            file: postgresql.yml
            service: firstapp-postgresql
